using System.Collections.ObjectModel;
using Finora.Application;
using Finora.Domain;
namespace Finora.App;
public sealed class RecurringViewModel:ViewModelBase
{
 private readonly IFinanceStore _store;private string _name="",_amount="",_processingResult="";private AccountSummary? _account;private Category? _category;private RecurrenceFrequency _frequency=RecurrenceFrequency.Monthly;private TransactionType _type=TransactionType.Expense;
 public RecurringViewModel(IFinanceStore store){_store=store;RefreshCommand=new AsyncCommand(LoadAsync);AddCommand=new AsyncCommand(AddAsync);ProcessNowCommand=new AsyncCommand(ProcessNowAsync);}
 public ObservableCollection<RecurrenceRule> Rules{get;}=[];public ObservableCollection<AccountSummary> Accounts{get;}=[];public ObservableCollection<Category> Categories{get;}=[];public IReadOnlyList<RecurrenceFrequency> Frequencies{get;}=Enum.GetValues<RecurrenceFrequency>();public IReadOnlyList<TransactionType> Types{get;}=[TransactionType.Expense,TransactionType.Income];public string Name{get=>_name;set=>SetProperty(ref _name,value);}public string Amount{get=>_amount;set=>SetProperty(ref _amount,value);}public AccountSummary? Account{get=>_account;set=>SetProperty(ref _account,value);}public Category? Category{get=>_category;set=>SetProperty(ref _category,value);}public RecurrenceFrequency Frequency{get=>_frequency;set=>SetProperty(ref _frequency,value);}public TransactionType Type{get=>_type;set=>SetProperty(ref _type,value);}public string ProcessingResult{get=>_processingResult;private set=>SetProperty(ref _processingResult,value);}public System.Windows.Input.ICommand RefreshCommand{get;}public System.Windows.Input.ICommand AddCommand{get;}public System.Windows.Input.ICommand ProcessNowCommand{get;}
 public Task LoadAsync()=>RunAsync(async()=>{Accounts.Clear();foreach(var a in await _store.GetAccountsAsync())Accounts.Add(a);Categories.Clear();foreach(var c in await _store.GetCategoriesAsync())if(!c.IsArchived)Categories.Add(c);Account??=Accounts.FirstOrDefault();await LoadRulesAsync();});
 private Task AddAsync()=>RunAsync(async()=>{if(Account is null)throw new InvalidOperationException("Choose an account.");if(string.IsNullOrWhiteSpace(Name))throw new InvalidOperationException("Rule name is required.");if(!decimal.TryParse(Amount,out var major)||major<=0)throw new InvalidOperationException("Enter a positive amount.");var today=DateOnly.FromDateTime(DateTime.Today);await _store.SaveRecurrenceRuleAsync(new RecurrenceRule{Name=Name.Trim(),Frequency=Frequency,Interval=1,StartsOn=today,NextDueOn=today,TransactionType=Type,AmountMinor=Money.FromMajorUnits(major,Account.Currency).MinorUnits,Currency=Account.Currency,AccountId=Account.Id,CategoryId=Category?.Id,DayOfMonth=today.Day});Name=Amount="";await LoadRulesAsync();});
 private Task ProcessNowAsync()=>RunAsync(async()=>{var count=await _store.ProcessDueRecurrencesAsync(DateOnly.FromDateTime(DateTime.Today));ProcessingResult=$"Processed {count} due item(s).";await LoadRulesAsync();});
 private async Task LoadRulesAsync(){Rules.Clear();foreach(var r in await _store.GetRecurrenceRulesAsync())Rules.Add(r);}
}
